In [1]:
a = 10
b = -20
c = 0

In [2]:
print(a)

10


In [3]:
type(a)

int

In [4]:
d='a'

In [7]:
type(d)

str

In [6]:
d = 'hello python'

In [8]:
3- 7

-4

In [9]:
print(3-4)

-1


In [10]:
print(type(3-4))

<class 'int'>


In [11]:
print(type(3-4.55))

<class 'float'>


In [12]:
1 == 1.0

True

In [13]:
0 != 0.0

False

In [14]:
print(type(0!=0.0))

<class 'bool'>


In [15]:
print(0!=0.0)

False


In [16]:
type(print(0!=0.0))

False


NoneType

In [17]:
a = 1

In [18]:
result = 0

In [22]:
result += a

In [23]:
result

3

In [24]:
type(result)

int

In [25]:
input()

dddd


'dddd'

In [28]:
type(input())

123


str

In [29]:
f"나는 {} 입니다"

SyntaxError: f-string: empty expression not allowed (3001644035.py, line 1)

In [33]:
a = '나정민','나정만'
f"나는 {a} 입니다."

"나는 ('나정민', '나정만') 입니다."

In [34]:
A = map(int, input().split())

1


In [35]:
type(A)

map

In [42]:
a = [1.2,2.5,3.7,4.6]
b = list(map(int, a))

In [43]:
b

[1, 2, 3, 4]

In [44]:
print(b)

[1, 2, 3, 4]


In [48]:
type(b)

list

In [49]:
type(b[0])

str

In [50]:
b= list(map(str,b)

AttributeError: 'list' object has no attribute 'spilt'

In [51]:
print(1, end="") 
print(2, end="")

12

In [64]:
a = """나랏말
싸미
중귁에
달아"""
a

'나랏말\n싸미\n중귁에\n달아'

In [65]:
print(a)

나랏말
싸미
중귁에
달아


In [66]:
b = '나랏말\n싸미\n중귁에\n달아'
print(b)

나랏말
싸미
중귁에
달아


In [68]:
lines = """파이썬도 배우고
장고도 배우고
할게 너무 많아"""
print(lines)

파이썬도 배우고
장고도 배우고
할게 너무 많아


In [69]:
text = "abcdefghijklmnopqrstuvwxyz"

In [70]:
text[0]

'a'

In [71]:
len(text)

26

In [72]:
type(text)

str

In [73]:
text

'abcdefghijklmnopqrstuvwxyz'

In [74]:
text[-1]

'z'

In [76]:
text[25] # 맨 마지막은 -1개

'z'

In [77]:
text2 = "hello python"

In [78]:
len(text2)

12

In [79]:
text[:12]

'abcdefghijkl'

In [81]:
text[3:-2]

'defghijklmnopqrstuvwx'

In [82]:
text[::2]

'acegikmoqsuwy'

In [84]:
text3 = int(1234567890)

In [85]:
text3

1234567890

In [86]:
text3 + 1

1234567891

In [88]:
weather = "20221005미세먼지양호함"
date = '20221005'
dust = '미세먼지양호함'

In [89]:
print("날짜", date)

날짜 20221005


In [90]:
print("날씨", dust)

날씨 미세먼지양호함


In [96]:
'오늘은 %s일 입니다.' % ("30일금요")

'오늘은 30일금요일 입니다.'

In [97]:
text2

'hello python'

In [100]:
text2.count('o')

2

In [101]:
text2.find('python')

6

In [102]:
text2.join('python')

'phello pythonyhello pythonthello pythonhhello pythonohello pythonn'

In [103]:
text2

'hello python'

In [104]:
text2.upper('hello')

TypeError: str.upper() takes no arguments (1 given)

In [118]:
text4='a,b,c,,d,e,f'
text4

'a,b,c,,d,e,f'

In [119]:
type(text4)

str

In [114]:
text2.upper()

'HELLO PYTHON'

In [115]:
text2.strip()

'hello python'

In [121]:
text4.replace('c','C')

'a,b,C,,d,e,f'

In [231]:
a2 = list('a,b,c,d,e,f')

In [234]:
a3 = list(1234)

TypeError: 'int' object is not iterable

In [232]:
type(a2)

list

In [233]:
a2

['a', ',', 'b', ',', 'c', ',', 'd', ',', 'e', ',', 'f']

In [132]:
type(a2[1])

str

In [133]:
len(a2)

6

In [135]:
a2[5]

'f'

In [136]:
a = [1,2,3]
a

[1, 2, 3]

In [140]:
a.append(4)

In [142]:
a.append("5")

In [143]:
a

[1, 2, 3, 4, '5', 4, '5']

In [148]:
a.insert(4,5)
a

[1, 2, 3, 4, 5, 5, 5, 5, '5', 4, '5']

In [149]:
lista = []
lista.extend([1,2,3])
lista

[1, 2, 3]

In [150]:
lista.insert(3,'100')

In [151]:
lista

[1, 2, 3, '100']

In [153]:
lista.append(['A,B'])
lista

[1, 2, 3, '100', ['A,B'], ['A,B']]

In [156]:
a =[1,2,3,4]
a

[1, 2, 3, 4]

In [157]:
a[0] = [10,20]
a

[[10, 20], 2, 3, 4]

In [170]:
a2 = [1,2,3,4]
a2[:1] = [100]
a2

[100, 2, 3, 4]

In [171]:
lista = [ 10, 99, 3, '사과', 73, '바나나' ]
lista

[10, 99, 3, '사과', 73, '바나나']

In [172]:
lista[3] = "apple"
lista

[10, 99, 3, 'apple', 73, '바나나']

In [173]:
lista[1:3] = 9,33
lista

[10, 9, 33, 'apple', 73, '바나나']

In [174]:
lista[4] = [73,74]
lista

[10, 9, 33, 'apple', [73, 74], '바나나']

In [175]:
a1 = [10, 20, 30, 40 ,50]
a2 = [10, 20, 30, 40 ,50]

In [176]:
a1[:1] = []

In [177]:
a1

[20, 30, 40, 50]

In [178]:
del a1[-1]
a1

[20, 30, 40]

In [179]:
a= [1,2,3,3,4,5]
a

[1, 2, 3, 3, 4, 5]

In [180]:
a.remove(5)
a

[1, 2, 3, 3, 4]

In [181]:
a.remove(3)
a

[1, 2, 3, 4]

In [182]:
a.pop()
a

[1, 2, 3]

In [183]:
a.pop(2)
a

[1, 2]

In [184]:
a = [10, -30, 57, -33, 71, 1, 34, -2]
a

[10, -30, 57, -33, 71, 1, 34, -2]

In [185]:
a.sort()

In [186]:
a

[-33, -30, -2, 1, 10, 34, 57, 71]

In [188]:
a.sort(reverse=True)
a

[71, 57, 34, 10, 1, -2, -30, -33]

In [189]:
b= [10, 71, 32, 46, 5, 95]
b

[10, 71, 32, 46, 5, 95]

In [190]:
print(b)

[10, 71, 32, 46, 5, 95]


In [193]:
b.reverse()
b

[95, 5, 46, 32, 71, 10]

In [194]:
b

[95, 5, 46, 32, 71, 10]

In [198]:
b.count(5)

1

In [199]:
len(b)

6

In [200]:
a = ['Life', 'is', 'too', 'short', 'you', 'need', 'python']
a

['Life', 'is', 'too', 'short', 'you', 'need', 'python']

In [204]:
print(a[4],a[2])

you too


In [205]:
len(a)

7

In [207]:
a.insert(0,len(a))

In [208]:
a

[7, 'Life', 'is', 'too', 'short', 'you', 'need', 'python']

In [209]:
lista = [1, 4, 9, 2, 6, 10]
lista

[1, 4, 9, 2, 6, 10]

In [210]:
lista.sort(reverse=True)
lista

[10, 9, 6, 4, 2, 1]

In [214]:
print("""lista[0]
lista[1]
lista[2]""")

lista[0]
lista[1]
lista[2]


In [2]:
d1= {'a' : [1, 2, 3],
     'b' : 100,
     'c' : {'key1' : ['파인애플', '포도', '바나나'], 'key2' : (55, 66)}}
d1

{'a': [1, 2, 3],
 'b': 100,
 'c': {'key1': ['파인애플', '포도', '바나나'], 'key2': (55, 66)}}

In [216]:
d1['a'][2]

3

In [218]:
d1['c']['key1'][:]

['파인애플', '포도', '바나나']

In [223]:
d1['c']['key1'][1:2]

['포도']

In [221]:
d1['c']['key2'][0]

55

In [224]:
d1 = {'a':1, 'b':2, 'c':3}
d1

{'a': 1, 'b': 2, 'c': 3}

In [225]:
d1['d'] = 4

In [226]:
d1

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [227]:
d1.update({'e':5,'f':6,'g':7})
d1

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7}

In [228]:
del d1['a']
d1

{'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7}

In [4]:
d1.values()

dict_values([[1, 2, 3], 100, {'key1': ['파인애플', '포도', '바나나'], 'key2': (55, 66)}])

In [5]:
d1.keys()

dict_keys(['a', 'b', 'c'])

In [6]:
d1.items()

dict_items([('a', [1, 2, 3]), ('b', 100), ('c', {'key1': ['파인애플', '포도', '바나나'], 'key2': (55, 66)})])

In [7]:
1 in d1

False

In [8]:
d1 = {'A':9, 'B':80, 'C':70}
d1

{'A': 9, 'B': 80, 'C': 70}

In [9]:
d1.update({'D' : 20, 'E' : 100, 'F' : 10})
d1

{'A': 9, 'B': 80, 'C': 70, 'D': 20, 'E': 100, 'F': 10}

In [10]:
d1['A'] = 90
d1

{'A': 90, 'B': 80, 'C': 70, 'D': 20, 'E': 100, 'F': 10}

In [44]:
a1 = d1['F']
f'최소 값 {a1}을 가진 key는 F 입니다.'

'최소 값 10을 가진 key는 F 입니다.'

In [45]:
min(d1.values())

10

In [58]:
a = [1,2,3,4]
for i in range(len(a)):
    print(i)

0
1
2
3


In [59]:
d1 = {'a':1, 'b':2, 'c':3}
for i in d1.items():
    print(i)

('a', 1)
('b', 2)
('c', 3)


In [60]:
def sum_func(num1, num2):
    result = num1 + num2
    return result

In [61]:
sum_func('a','b')

'ab'

In [64]:
def average(*scores):
    print(scores)
    total = 0
    for score in scores:
        total += score
    return f"총점은 {total}이고 평균은 {total/len(scores)} 입니다."

average(10,20,30,40,50)    

(10, 20, 30, 40, 50)


'총점은 150이고 평균은 30.0 입니다.'

In [70]:
def aa(*scores):
    A = []
    B = []
    for score in scores:
        if score > 100:
            A.append(score)
        elif score <= 100:
            B.append(score)
    return f"100보다 큰 수는 {A}이고 100보다 작거나 같은 수는 {B}입니다."
aa(100,12,42,112,190,2000)

'100보다 큰 수는 [112, 190, 2000]이고 100보다 작거나 같은 수는 [100, 12, 42]입니다.'

In [ ]:
def test(**kwargs)

In [71]:
lista = [1,2,3,4,5,6,5]

In [72]:
lista

[1, 2, 3, 4, 5, 6, 5]

In [73]:
lista.items()

AttributeError: 'list' object has no attribute 'items'

In [125]:
import numpy as np
import matplotlib.pyplot as plt

def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [76]:
np.__version__

'1.21.5'

In [77]:
data = [1,2,3,4,5,6,7]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [78]:
arr.dtype

dtype('int32')

In [79]:
arr.shape

(7,)

In [80]:
len(arr)

7

In [81]:
arr.ndim

1

In [82]:
arr.size

7

In [84]:
arr.reshape(7,1)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [86]:
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (7,)
    ndim : 1
    dtype : int32
    array data : 
 [1 2 3 4 5 6 7]


In [92]:
arr1 = np.zeros((3,4), dtype=int)
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [93]:
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [94]:
data = [[1,2,3],
        [4,5,6]]

In [95]:
arr = np.array(data)

In [96]:
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]]


In [100]:
arr2 = np.full_like(arr, 1)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 1 1]
 [1 1 1]]


In [153]:
arr = np.linspace(1,1000,num=1000, dtype = int)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (1000,)
    ndim : 1
    dtype : int32
    array data : 
 [   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  

In [110]:
n2 = []
n3 = []
for i in arr:
    if i%2 ==0:
        n2.append(i)
    elif i%2 != 0:
        n3.append(i)
print(n2,n3)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420, 42

In [111]:
arr = np.arange(1,1001)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (1000,)
    ndim : 1
    dtype : int32
    array data : 
 [   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  

In [132]:
arr = np.random.randint(46, size=(6,5))
arr

array([[ 1, 21, 15, 43, 38],
       [24, 19, 24, 30,  5],
       [41, 13,  8, 23, 44],
       [16, 12, 21, 13,  1],
       [15,  7, 17, 18, 31],
       [ 8,  0, 28, 15, 17]])

In [134]:
np.random.seed(45)

In [136]:
np.random.random((6,5))

array([[0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ],
       [0.47280797, 0.048522  , 0.16332445, 0.11595071, 0.62739168],
       [0.85618205, 0.65010242, 0.99072168, 0.47035075, 0.61829448],
       [0.28266721, 0.97600332, 0.673068  , 0.44053089, 0.28968734],
       [0.50969968, 0.1124609 , 0.22695479, 0.4785523 , 0.24275816],
       [0.38798252, 0.81887343, 0.07454079, 0.92314954, 0.22489608]])

In [144]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(4,13).reshape(3,3)
c = np.arange(10,22).reshape(3,4)

In [145]:
np_print(a)
np_print(b)
np_print(c)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [146]:
a+ b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [147]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [148]:
np.add(a,b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [149]:
np.subtract(a,b)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [151]:
np.divide(a,b)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [152]:
np.multiply(a,b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [161]:
sosu=[]
for i in np.sqrt(arr):
    sosu.append(int(i))
print(sosu)

[1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16

In [162]:
len(sosu)

1000

In [163]:
np.dot(a,b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

In [164]:
np_print(a)
np_print(b)
np_print(c)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [165]:
a.sum()

45

In [166]:
np.sum(a)

45

In [167]:
a.sum(axis=1)

array([ 6, 15, 24])

In [168]:
a.sum(axis=0)

array([12, 15, 18])

In [169]:
min(arr)

1

In [170]:
max(arr)

1000

In [171]:
arr.mean()

500.5

In [174]:
np.median(arr)

500.5

In [175]:
x= np.arange(1,5).reshape(1,4)
y= np.arange(1,5).reshape(4,1)

In [176]:
np_print(x)
np_print(y)


    type : <class 'numpy.ndarray'>
    shape : (1, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3 4]]

    type : <class 'numpy.ndarray'>
    shape : (4, 1)
    ndim : 2
    dtype : int32
    array data : 
 [[1]
 [2]
 [3]
 [4]]


In [2]:
pos=[0]*8
pos

[0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
def put() -> None:
    for i in range(8):
        pritn(f'{pos[i]:2}', end="")
    print()
def